[package]
name = "sloth-pasta"
version = "0.1.0"
description = "Pasta VDF"
edition = "2018"
license = "MIT"
repository = "https://github.com/supranational/sloth-pasta"
include = [
    "/src",
    "/Cargo.toml",
]

[build-dependencies]
cc = "^1.0"
